/* C code */
int result = 0;
for(int i=0; i<100; i++){
result += i; }

In [1]:
import numpy as np

In [2]:
result =0
for i in range(100):
    result += i

In [3]:
result

4950

In [5]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
type(L[0])

int

In [7]:
L2 = [str(c) for c in L] 
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [9]:

type(L2[0])

str

In [10]:
L3 = [True, "2", 3.0, 4]

Because of Python’s dynamic typing, we can even create heterogeneous lists:

In [12]:
[type(item) for item in L3]

[bool, str, float, int]

In [14]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
type(A[0])

int

In [17]:
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [18]:
np.array([3.14, 4, 2,3])

array([3.14, 4.  , 2.  , 3.  ])

In [19]:
#nested lists result in multidimensional array
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [20]:
#create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
# Create a 3x5 floating-point array filled with 1s 
np.ones((3, 5), dtype=float)


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
# Create a 3x5 array filled with 3.14 
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [23]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function) 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
# Create an array of five values evenly spaced between 0 and 1 
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
# Create a 3x3 array of uniformly distributed # random values between 0 and 1
np.random.random((3, 3))

array([[0.06461335, 0.30207327, 0.76093735],
       [0.79659122, 0.19025175, 0.43149695],
       [0.11109265, 0.34132261, 0.92762031]])

In [26]:
# Create a 3x3 array of normally distributed random values # with mean 0 and standard deviation 1 
np.random.normal(0, 1, (3, 3))

array([[ 0.27466363, -0.22508095,  0.23260733],
       [ 0.42894194,  1.70583229,  0.29473233],
       [-0.56491722, -0.09833199,  1.33357201]])

In [27]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 8, 6],
       [5, 1, 7],
       [7, 4, 8]])

In [28]:
# Create a 3x3 identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [29]:
np.empty(3)

array([1., 1., 1.])

In [30]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [31]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

# Numpy Array Attributes

In [32]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [35]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [36]:
print("x3 ndim: ", x3.ndim) 
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)


x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [37]:
print("dtype:", x3.dtype)

dtype: int64


In [38]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


# Array Indexing and Slicing

In [39]:
x1

array([5, 0, 3, 3, 7, 9])

In [40]:
x1[0]

5

In [41]:
x1[4]

7

In [42]:
x1[-1]

9

In [43]:
x1[-2]

7

In [44]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x2[0,0]

3

In [46]:
x2[2,0]

1

In [47]:
x2[2,-1]

7

In [48]:
x2[0,0]

3

In [50]:
x1[0]=3.14159 #this will be truncated
x1


array([3, 0, 3, 3, 7, 9])

# Array Slicing: Accessing Subarrays

### One-dimensional subarrays

In [52]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x[:5] #first five elements

array([0, 1, 2, 3, 4])

In [54]:
x[5:] #elements after index 5

array([5, 6, 7, 8, 9])

In [55]:
x[4:7] #middle subarray

array([4, 5, 6])

In [56]:
x[::2] #every other element

array([0, 2, 4, 6, 8])

In [57]:
x[1::2] #every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [58]:
x[::-1] #all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [59]:
x[5::-2] #reversed every other from index 5

array([5, 3, 1])

### Multidimensional subarrays

In [60]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [61]:
x2[:2,:3] #two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [62]:
x2[:3, ::2] #all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 7]])

In [63]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

Accessing array rows and columns

In [64]:
print(x2[:, 0]) # first column of x2

[3 7 1]


In [65]:
print(x2[0, :]) # first row of x2


[3 5 2 4]


In [66]:
print(x2[0]) # equivalent to x2[0, :]

[3 5 2 4]
